server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  mvc:
    # URL响应地址（Springboot默认为/**)
    static-path-pattern: /**
  web:
    resources:
      # 静态文件地址，保留官方内容后，进行追加
      static-locations: classpath:/static,classpath:/templates
  servlet:
    multipart:
      max-file-size: 50MB
# 加载mybati的全局配置文件
mybatis:
  mapper-locations: classpath:com/system/mapper/*.xml

